In [1]:
import numpy as np

In [2]:
np.array([10, 'apple'])
np.array(['a', 'b', 'c'])
np.array(['cat', 'bat', 'mat'])

array(['10', 'apple'], dtype='<U21')

array(['a', 'b', 'c'], dtype='<U1')

array(['cat', 'bat', 'mat'], dtype='<U3')

In [3]:
[
    ['apple', 'banana'],
    ['kiwi']
]

np.array([
    ['apple', 'banana'],
    ['kiwi', 'pineapple'],
    ['orange', 'NA']
]).shape

[['apple', 'banana'], ['kiwi']]

(3, 2)

In [4]:
lst = np.array([
    ['apple', 'banana'],
    ['kiwi', 'pineapple'],
    ['orange', 'NA']
])

lst[0, 1]
lst[0][1]

np.str_('banana')

np.str_('banana')

In [5]:
def greet(name):
  return f'hello {name}'


for name in np.array(['vidu', 'rahul', 'vishnu']):
  greet(name)

'hello vidu'

'hello rahul'

'hello vishnu'

In [6]:
np.array([6, 7, 8]) ** 2
np.array([6, 7, 8]) * np.array([2, 3, 10])
np.array([6, 7, 8]) + np.array([2, 3, 10])
# np.array([6, 7, 8]) + np.array([2, 3, 10, 15]) # fails, not homogenous

array([36, 49, 64])

array([12, 21, 80])

array([ 8, 10, 18])

In [7]:
np.array([6, 7, 8]) > 2
np.array([6, 7, 8, 10, 5]) >= 7

array([ True,  True,  True])

array([False,  True,  True,  True, False])

In [8]:
np.array([4, 1, 9, 10, 4, 5]) >= 7
np.where(np.array([4, 1, 9, 10, 4, 5]) >= 7)

array([False, False,  True,  True, False, False])

(array([2, 3]),)

In [9]:
['apple'] * 7
np.array(['apple'] * 7)

['apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple']

array(['apple', 'apple', 'apple', 'apple', 'apple', 'apple', 'apple'],
      dtype='<U5')

In [10]:
np.array([4, 5, 8, 10, 11, 15, 20]) % 2 == 0
np.where(np.array([4, 5, 8, 10, 11, 15, 20]) % 2 == 0,
         np.array(['apple'] * 7),
         np.array(['banana'] * 7))

array([ True, False,  True,  True, False, False,  True])

array(['apple', 'banana', 'apple', 'apple', 'banana', 'banana', 'apple'],
      dtype='<U6')